name: nitro_analysis_options
version: 1.0.0
description: Common analysis options for all packages
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.7
  dart_code_metrics: ^4.9.1