name: nitro_repositories
description: Repositories to receive/save data
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  nitro_analysis_options:
    path: ../nitro_analysis_options
  nitro_auth_api_client:
    path: ../nitro_auth_api_client

dev_dependencies:
  build_runner: ^2.1.7
  dart_dot_reporter: ^1.0.4
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0